version: '3.8'

services:
  backend:
    build: ./backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: expense-tracker-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_tracker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  pdf-extractor:
    build: ./pdf-extractor
    container_name: pdf-extractor
    ports:
      - "5001:5000"
    volumes:
      - ./pdf-extractor:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  db_data: