version: '3.8'

services:
  backend:
    build: ./backend
    container_name: laravel_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env